dataset: covid # time series only models
target: percent_ili #targets: percent_ili, flu_hospitalizations, covid_hospitalizations
data_name: percent_ili

exp_id: 3
data_id: 3
test_time: 202412 # should be 4 timesteps before the last date
pred_starting_time: 202340 #want to start predicting the epi year before test_time

# over-writing parameters
model_name: gru
model_parameters:
  hidden_dim: 128
  meta_emb_dim: 16
training_parameters:
  batch_size: 32
  lr: 0.001
  gamma: 0.95

# model_name: transformer
# model_parameters:
#   hidden_dim: 128
#   num_layers: 2
#   num_heads: 4
#   dropout: 0.1

# training_parameters:
#   batch_size: 32
#   lr: 0.0003
#   gamma: 0.1
#   patience: 50

# model_name: colagnn #cnnrnnres #arima

model_variant: default
description: covid


aheads: [1, 2, 3, 4]
smooth: False
fix_window: True # False will train on the entire sequence or curve
true_scale: True
total_steps: 1000  
skip_beginning: 0
multi_seed: False


# rft
region_fine_tuning: False #True
rft_epochs: 20
rft_batch_size: 32


# week retraining: if False, use model state dict from previous week
week_retrain: True
week_retrain_epochs: 100 
# skip weeks, train once and use the pretrained model state for the next several weeks
week_retrain_period: 5
